### ISSUE TITLE
Reasoning behind project

### ISSUE THREAD

**Issue by yasoob** [simonw/sphinx-to-sqlite#1]
Hi Simon!

This isn't really an issue so feel free to close this. I am just curious behind the motivation for this project. What is the usecase and why would anyone want this? :)

Have a good day and best of luck with the project!

~ Yasoob

**Comment by simonw** [comment]
Hi Yasoob,

That's a good question! I'm not quite ready to announce this yet, but the goal is to help me build a single combined search engine for all kinds of things relating to my Datasette project.

I want to use https://github.com/dogsheep/dogsheep-beta to build a search engine that searches GitHub issues, releases and documentation across all of the projects I've built under the Datasette umbrella.

`sphinx-to-sqlite` lets me build a SQLite search index of my documentation - I've got that running in Datasette here https://latest-docs.datasette.io/docs/sections?_search=pytest

The next step is to plug in other searchable content and put an interface on top of it all.
